export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const ARTWORK_LIST_REQUEST = "ARTWORK_LIST_REQUEST";
export const ARTWORK_LIST_SUCCESS = "ARTWORK_LIST_SUCCESS";
export const ARTWORK_LIST_FAIL = "ARTWORK_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const ARTWORK_DETAILS_REQUEST = "ARTWORK_DETAILS_REQUEST";
export const ARTWORK_DETAILS_SUCCESS = "ARTWORK_DETAILS_SUCCESS";
export const ARTWORK_DETAILS_FAIL = "ARTWORK_DETAILS_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";


export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";


export const FRAME_FILTERS_REQUEST = "FRAME_FILTERS_REQUEST";
export const FRAME_FILTERS_SUCCESS = "FRAME_FILTERS_SUCCESS";
export const FRAME_FILTERS_FAIL = "FRAME_FILTERS_FAIL";

export const ARTWORK_FILTERS_REQUEST = "ARTWORK_FILTERS_REQUEST";
export const ARTWORK_FILTERS_SUCCESS = "ARTWORK_FILTERS_SUCCESS";
export const ARTWORK_FILTERS_FAIL = "ARTWORK_FILTERS_FAIL";

